export const topMeals = [
    {
        image:"https://media.istockphoto.com/id/1303119992/photo/pizza_margerita.jpg?s=612x612&w=0&k=20&c=0HZZMC10ySBYvMVAKUNzknkQ1E74q8NKwTV5_K6WK6M=",
        title:"Pizza"
    },
    {
        image:"",
        title:"Burger"
    },
    {
        image:"",
        title:"Sandwich"
    },
    {
        image:"",
        title:"Biryani"
    },
    {
        image:"",
        title:"Cake"
    },
    {
        image:"",
        title:"Chinese"
    },
    {
        image:"",
        title:"Thali"
    },
    {
        image:"",
        title:"Sweets"
    },
    {
        image:"",
        title:"South-Indian"
    },
    {
        image:"",
        title:"Rolls"
    },
    {
        image:"",
        title:"Chiken",
    },
    {
        image:"",
        title:"Noodles"
    }

]